// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {terminal} from '../models';

export function AssignServerTerminalProfile(arg1:domain.AssignServerTerminalProfileRequest):Promise<domain.Connection>;

export function BeginAlertSession(arg1:domain.BeginAlertSessionRequest):Promise<void>;

export function CancelBatchCommandServer(arg1:domain.CancelBatchCommandServerRequest):Promise<void>;

export function CancelBatchCommandTask(arg1:domain.CancelBatchCommandTaskRequest):Promise<void>;

export function CancelNetworkDiagnostic(arg1:domain.CancelNetworkDiagnosticRequest):Promise<void>;

export function CancelSystemServiceRequests(arg1:domain.ServiceManagerServerRequest):Promise<void>;

export function CheckServiceManager(arg1:domain.ServiceManagerServerRequest):Promise<domain.ServiceManagerCapability>;

export function CheckShortcutConflicts(arg1:domain.ShortcutConflictCheckRequest):Promise<domain.ShortcutConflictCheckResponse>;

export function CheckTunnelRemoteListen(arg1:domain.CheckTunnelRemoteListenRequest):Promise<domain.TunnelRuntime>;

export function ClearBatchCommandTask(arg1:string):Promise<void>;

export function ClearCommandHistory(arg1:number):Promise<void>;

export function ClearResolvedAlertHistory(arg1:domain.ClearResolvedAlertHistoryRequest):Promise<void>;

export function CloseLocalTerminal(arg1:string):Promise<void>;

export function CloseNetworkInspectionContext(arg1:domain.CloseNetworkInspectionContextRequest):Promise<void>;

export function CloseSftp(arg1:number):Promise<void>;

export function CloseSftpContext(arg1:domain.SFTPContextRequest):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function Connect(arg1:domain.ConnectRequest):Promise<void>;

export function CreateCommandFavorite(arg1:domain.SaveCommandFavoriteRequest):Promise<domain.CommandFavorite>;

export function CreateKeyVaultEntry(arg1:domain.SaveKeyVaultEntryRequest):Promise<domain.KeyVaultEntry>;

export function CreateTerminalProfile(arg1:domain.SaveTerminalProfileRequest):Promise<domain.TerminalProfile>;

export function CreateTunnelProfile(arg1:domain.SaveTunnelProfileRequest):Promise<domain.TunnelProfile>;

export function DeleteCommandFavorite(arg1:string):Promise<void>;

export function DeleteCommandHistory(arg1:string):Promise<void>;

export function DeleteConnection(arg1:number):Promise<void>;

export function DeleteGroup(arg1:number):Promise<void>;

export function DeleteKeyVaultEntry(arg1:domain.DeleteKeyVaultEntryRequest):Promise<domain.DeleteKeyVaultEntryResponse>;

export function DeleteKeyVaultPassphrase(arg1:number):Promise<void>;

export function DeleteSavedCredential(arg1:number):Promise<void>;

export function DeleteTerminalProfile(arg1:domain.DeleteTerminalProfileRequest):Promise<domain.DeleteTerminalProfileResponse>;

export function DeleteTunnelProfile(arg1:number):Promise<void>;

export function DisableSystemService(arg1:domain.SystemServiceActionRequest):Promise<domain.SystemServiceActionResponse>;

export function Disconnect(arg1:number):Promise<void>;

export function DisconnectServer(arg1:number):Promise<void>;

export function DockerBatchRemoveContainers(arg1:domain.DockerBatchContainerRequest):Promise<domain.DockerBatchContainerResponse>;

export function DockerBatchRestartContainers(arg1:domain.DockerBatchContainerRequest):Promise<domain.DockerBatchContainerResponse>;

export function DockerBatchStartContainers(arg1:domain.DockerBatchContainerRequest):Promise<domain.DockerBatchContainerResponse>;

export function DockerBatchStopContainers(arg1:domain.DockerBatchContainerRequest):Promise<domain.DockerBatchContainerResponse>;

export function DockerCheck(arg1:number):Promise<domain.DockerAvailability>;

export function DockerComposeCheck(arg1:number):Promise<domain.DockerComposeCapability>;

export function DockerComposeGetLogs(arg1:domain.DockerComposeLogsRequest):Promise<domain.DockerComposeLogsSnapshot>;

export function DockerComposeGetServiceDetail(arg1:domain.DockerComposeServiceDetailRequest):Promise<domain.DockerComposeService>;

export function DockerComposeGetServices(arg1:domain.DockerComposeProjectRequest):Promise<domain.DockerComposeServicesResponse>;

export function DockerComposeListProjects(arg1:domain.DockerComposeProjectsRequest):Promise<Array<domain.DockerComposeProject>>;

export function DockerGetContainerInspectSummary(arg1:domain.DockerContainerRequest):Promise<domain.DockerInspectSummary>;

export function DockerGetContainerLogs(arg1:domain.DockerLogsRequest):Promise<string>;

export function DockerGetContainerStats(arg1:domain.DockerContainerRequest):Promise<domain.DockerContainerStats>;

export function DockerListContainers(arg1:domain.DockerListContainersRequest):Promise<Array<domain.DockerContainer>>;

export function DockerRemoveContainer(arg1:domain.DockerContainerRequest):Promise<void>;

export function DockerRestartContainer(arg1:domain.DockerContainerRequest):Promise<void>;

export function DockerStartContainer(arg1:domain.DockerContainerRequest):Promise<void>;

export function DockerStartLogStream(arg1:domain.DockerLogStreamRequest):Promise<string>;

export function DockerStartStatsWatch(arg1:domain.DockerStatsWatchRequest):Promise<string>;

export function DockerStopContainer(arg1:domain.DockerContainerRequest):Promise<void>;

export function DockerStopLogStream(arg1:domain.DockerStopLogStreamRequest):Promise<void>;

export function DockerStopStatsWatch(arg1:domain.DockerStopStatsWatchRequest):Promise<void>;

export function DuplicateTerminalProfile(arg1:string):Promise<domain.TerminalProfile>;

export function EnableRemoteForwardAccess(arg1:domain.RemoteForwardAccessRequest):Promise<domain.RemoteForwardAccessEnableResult>;

export function EnableRemoteForwardAccessAndRestart(arg1:domain.RemoteForwardAccessRestartRequest):Promise<domain.RemoteForwardAccessRestartResult>;

export function EnableSystemService(arg1:domain.SystemServiceActionRequest):Promise<domain.SystemServiceActionResponse>;

export function ExportBackup(arg1:domain.BackupExportRequest):Promise<domain.BackupExportResult>;

export function GetAppVersion():Promise<domain.AppVersionInfo>;

export function GetAuthenticationState(arg1:number):Promise<domain.AuthenticationState>;

export function GetBatchCommandTask(arg1:string):Promise<domain.BatchCommandTask>;

export function GetConnectionState(arg1:number):Promise<domain.ConnectionRuntimeState>;

export function GetDefaultSettings():Promise<domain.AppSettings>;

export function GetLocalDrives():Promise<Array<domain.LocalDrive>>;

export function GetLocalExplorerHome():Promise<domain.LocalExplorerHome>;

export function GetLocalResourceSnapshot():Promise<domain.LocalResourceSnapshot>;

export function GetLocalTerminalCapabilities():Promise<domain.LocalTerminalCapabilities>;

export function GetLocalTerminalState(arg1:string):Promise<domain.LocalTerminalState>;

export function GetMonitorNetworkInterface(arg1:number):Promise<domain.MonitorNetworkInterfacePreference>;

export function GetMonitorSnapshot(arg1:number):Promise<domain.MonitorSnapshot>;

export function GetNetworkEndpointSnapshot(arg1:domain.NetworkEndpointSnapshotRequest):Promise<domain.NetworkEndpointSnapshot>;

export function GetProcessDetail(arg1:domain.GetProcessDetailRequest):Promise<domain.ProcessDetail>;

export function GetResolvedTerminalProfile(arg1:domain.ResolveTerminalProfileRequest):Promise<domain.TerminalProfile>;

export function GetSettings():Promise<domain.AppSettings>;

export function GetSftpContextState(arg1:domain.SFTPContextRequest):Promise<domain.SFTPState>;

export function GetSftpState(arg1:number):Promise<domain.SFTPState>;

export function GetStartupLocalTerminalRequest():Promise<domain.LocalTerminalStartupRequest>;

export function GetSystemServiceDetail(arg1:domain.SystemServiceActionRequest):Promise<domain.SystemServiceDetail>;

export function GetSystemServiceJournal(arg1:domain.SystemServiceJournalRequest):Promise<domain.SystemServiceJournalResponse>;

export function GetTunnelState(arg1:string):Promise<domain.TunnelRuntime>;

export function ImportBackup(arg1:domain.BackupImportRequest):Promise<domain.BackupImportResult>;

export function IncrementCommandFavoriteUse(arg1:string):Promise<domain.CommandFavorite>;

export function InspectBackup(arg1:domain.BackupInspectRequest):Promise<domain.BackupPreview>;

export function InspectRemoteForwardAccess(arg1:domain.RemoteForwardAccessRequest):Promise<domain.RemoteForwardAccessInspectResult>;

export function ListAlertHistory(arg1:domain.ListAlertHistoryRequest):Promise<Array<domain.AlertHistoryEvent>>;

export function ListBatchCommandTasks():Promise<Array<domain.BatchCommandTask>>;

export function ListCommandFavorites(arg1:domain.ListCommandFavoritesRequest):Promise<Array<domain.CommandFavorite>>;

export function ListCommandHistory(arg1:domain.ListCommandHistoryRequest):Promise<Array<domain.CommandHistoryEntry>>;

export function ListCommandSuggestions(arg1:domain.ListCommandSuggestionsRequest):Promise<Array<domain.CommandSuggestion>>;

export function ListConnections():Promise<Array<domain.Connection>>;

export function ListGroups():Promise<Array<domain.Group>>;

export function ListKeyVaultEntries():Promise<Array<domain.KeyVaultEntry>>;

export function ListLocalDirectory(arg1:domain.LocalDirectoryRequest):Promise<domain.LocalDirectoryListing>;

export function ListLocalTerminals():Promise<Array<domain.LocalTerminalState>>;

export function ListLogs(arg1:number):Promise<Array<domain.LogEntry>>;

export function ListNetworkDiagnosticTasks(arg1:number):Promise<Array<domain.NetworkDiagnosticTask>>;

export function ListNetworkInterfaces(arg1:domain.ListNetworkInterfacesRequest):Promise<domain.ListNetworkInterfacesResponse>;

export function ListProcesses(arg1:domain.ListProcessesRequest):Promise<domain.ProcessListResponse>;

export function ListSystemServices(arg1:domain.ServiceManagerServerRequest):Promise<domain.SystemServiceListResponse>;

export function ListTerminalProfiles():Promise<Array<domain.TerminalProfile>>;

export function ListTunnelProfiles():Promise<Array<domain.TunnelProfile>>;

export function ListTunnels(arg1:domain.ListTunnelsRequest):Promise<Array<domain.TunnelRuntime>>;

export function LogFrontendError(arg1:string):Promise<void>;

export function MarkAlertHistoryRead(arg1:domain.MarkAlertHistoryReadRequest):Promise<void>;

export function MarkAllAlertHistoryRead(arg1:domain.MarkAllAlertHistoryReadRequest):Promise<void>;

export function MigrateLegacyPrivateKey(arg1:domain.SaveKeyVaultEntryRequest):Promise<domain.KeyVaultEntry>;

export function OpenLocalPath(arg1:domain.LocalPathRequest):Promise<void>;

export function OpenLocalTerminal(arg1:domain.LocalTerminalOpenRequest):Promise<domain.LocalTerminalOpenResponse>;

export function OpenNetworkInspectionContext(arg1:domain.OpenNetworkInspectionContextRequest):Promise<domain.OpenNetworkInspectionContextResponse>;

export function OpenSftp(arg1:domain.ConnectRequest):Promise<domain.SFTPState>;

export function OpenTerminal(arg1:domain.OpenTerminalRequest):Promise<terminal.SessionInfo>;

export function PersistAlertHistoryEvent(arg1:domain.PersistAlertHistoryEventRequest):Promise<domain.AlertHistoryPersistResult>;

export function PersistWindowState():Promise<void>;

export function ProbeConnectionReachability(arg1:number):Promise<domain.ConnectionReachabilityResult>;

export function ProbeHostKey(arg1:number):Promise<domain.HostKeyProbeResult>;

export function ReadSftpDir(arg1:domain.SFTPListRequest):Promise<domain.SFTPListResult>;

export function ReconnectSftp(arg1:domain.ConnectRequest):Promise<domain.SFTPState>;

export function ReconnectTerminal(arg1:domain.ReconnectTerminalRequest):Promise<terminal.SessionInfo>;

export function RecordBatchCommandHistory(arg1:domain.RecordBatchCommandHistoryRequest):Promise<domain.RecordBatchCommandHistoryResult>;

export function RecordCommandHistory(arg1:domain.RecordCommandHistoryRequest):Promise<domain.RecordCommandHistoryResult>;

export function RelaunchElevatedLocalTerminal(arg1:domain.LocalTerminalElevatedRelaunchRequest):Promise<void>;

export function ReorderServers(arg1:domain.ReorderServersRequest):Promise<Array<domain.Connection>>;

export function ResetHostKeyTrust(arg1:number):Promise<void>;

export function ResizeLocalTerminal(arg1:domain.LocalTerminalResizeRequest):Promise<void>;

export function ResizeTerminal(arg1:domain.TerminalResizeRequest):Promise<void>;

export function RestartSystemService(arg1:domain.SystemServiceActionRequest):Promise<domain.SystemServiceActionResponse>;

export function RestartTunnel(arg1:domain.RestartTunnelRequest):Promise<domain.TunnelRuntime>;

export function RevealLocalPath(arg1:domain.LocalPathRequest):Promise<void>;

export function SaveConnection(arg1:domain.SaveConnectionRequest):Promise<domain.Connection>;

export function SaveConnectionConfig(arg1:domain.SaveConnectionConfigRequest):Promise<domain.SaveConnectionConfigResult>;

export function SaveGroup(arg1:domain.Group):Promise<domain.Group>;

export function SaveSettings(arg1:domain.AppSettings):Promise<domain.AppSettings>;

export function SelectBackupExportPath():Promise<string>;

export function SelectBackupImportFile():Promise<string>;

export function SelectLocalDownloadDirectory():Promise<string>;

export function SelectLocalUploadDirectory():Promise<string>;

export function SelectLocalUploadFiles():Promise<Array<string>>;

export function SelectPrivateKeyFile():Promise<string>;

export function SetDefaultTerminalProfile(arg1:string):Promise<domain.AppSettings>;

export function SetMonitorNetworkInterface(arg1:domain.SetMonitorNetworkInterfaceRequest):Promise<domain.MonitorNetworkInterfacePreference>;

export function SftpCancelTransfer(arg1:domain.SFTPTransferCancelRequest):Promise<void>;

export function SftpDelete(arg1:domain.SFTPDeleteRequest):Promise<void>;

export function SftpDownload(arg1:domain.SFTPTransferRequest):Promise<domain.SFTPTransferState>;

export function SftpDownloadDirectory(arg1:domain.SFTPDownloadDirectoryRequest):Promise<domain.SFTPTransferState>;

export function SftpGetRemoteItemProperties(arg1:domain.SFTPItemPropertiesRequest):Promise<domain.SFTPItemProperties>;

export function SftpGoHome(arg1:domain.SFTPContextRequest):Promise<domain.SFTPListResult>;

export function SftpGoParent(arg1:domain.SFTPContextRequest):Promise<domain.SFTPListResult>;

export function SftpInspectDelete(arg1:domain.SFTPInspectDeleteRequest):Promise<domain.SFTPInspectDeleteResponse>;

export function SftpMkdir(arg1:domain.SFTPMkdirRequest):Promise<void>;

export function SftpPauseTransfer(arg1:domain.SFTPTransferControlRequest):Promise<domain.SFTPTransferControlResponse>;

export function SftpReadTextFile(arg1:domain.SFTPReadTextFileRequest):Promise<domain.SFTPReadTextFileResult>;

export function SftpRename(arg1:domain.SFTPRenameRequest):Promise<void>;

export function SftpResumeTransfer(arg1:domain.SFTPTransferControlRequest):Promise<domain.SFTPTransferControlResponse>;

export function SftpStat(arg1:domain.SFTPStatRequest):Promise<domain.SFTPEntry>;

export function SftpUpdateRemoteItemPermissions(arg1:domain.SFTPUpdateItemPermissionsRequest):Promise<domain.SFTPItemProperties>;

export function SftpUpload(arg1:domain.SFTPTransferRequest):Promise<domain.SFTPTransferState>;

export function SftpUploadDirectory(arg1:domain.SFTPUploadDirectoryRequest):Promise<domain.SFTPTransferState>;

export function SftpWriteTextFile(arg1:domain.SFTPWriteTextFileRequest):Promise<domain.SFTPWriteTextFileResult>;

export function ShowLocalPathProperties(arg1:domain.LocalPathRequest):Promise<void>;

export function SignalProcess(arg1:domain.SignalProcessRequest):Promise<domain.SignalProcessResponse>;

export function StartBatchCommand(arg1:domain.StartBatchCommandRequest):Promise<domain.BatchCommandTask>;

export function StartNetworkDiagnostic(arg1:domain.StartNetworkDiagnosticRequest):Promise<domain.NetworkDiagnosticTask>;

export function StartProcessWatch(arg1:domain.StartProcessWatchRequest):Promise<string>;

export function StartSystemService(arg1:domain.SystemServiceActionRequest):Promise<domain.SystemServiceActionResponse>;

export function StartSystemServiceJournalFollow(arg1:domain.SystemServiceJournalRequest):Promise<domain.SystemServiceJournalFollowResponse>;

export function StartTunnel(arg1:domain.StartTunnelRequest):Promise<domain.TunnelRuntime>;

export function StopProcessWatch(arg1:domain.StopProcessWatchRequest):Promise<void>;

export function StopSystemService(arg1:domain.SystemServiceActionRequest):Promise<domain.SystemServiceActionResponse>;

export function StopSystemServiceJournalFollow(arg1:domain.StopSystemServiceJournalFollowRequest):Promise<void>;

export function StopTunnel(arg1:domain.StopTunnelRequest):Promise<void>;

export function TestConnection(arg1:domain.ConnectRequest):Promise<domain.TestConnectionResult>;

export function TrustHostKey(arg1:domain.TrustHostKeyRequest):Promise<void>;

export function UpdateCommandFavorite(arg1:domain.SaveCommandFavoriteRequest):Promise<domain.CommandFavorite>;

export function UpdateCommandHistory(arg1:domain.UpdateCommandHistoryRequest):Promise<domain.UpdateCommandHistoryResult>;

export function UpdateKeyVaultEntry(arg1:domain.SaveKeyVaultEntryRequest):Promise<domain.KeyVaultEntry>;

export function UpdateKeyVaultPassphrase(arg1:number,arg2:string):Promise<domain.KeyVaultEntry>;

export function UpdateTerminalProfile(arg1:domain.SaveTerminalProfileRequest):Promise<domain.TerminalProfile>;

export function UpdateTunnelProfile(arg1:domain.SaveTunnelProfileRequest):Promise<domain.TunnelProfile>;

export function ValidatePrivateKeyFile(arg1:domain.ValidatePrivateKeyFileRequest):Promise<domain.PrivateKeyValidationResult>;

export function WriteLocalTerminal(arg1:domain.LocalTerminalWriteRequest):Promise<void>;

export function WriteTerminal(arg1:domain.TerminalWriteRequest):Promise<void>;
