// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignServerTerminalProfile(arg1) {
  return window['go']['main']['App']['AssignServerTerminalProfile'](arg1);
}

export function BeginAlertSession(arg1) {
  return window['go']['main']['App']['BeginAlertSession'](arg1);
}

export function CancelBatchCommandServer(arg1) {
  return window['go']['main']['App']['CancelBatchCommandServer'](arg1);
}

export function CancelBatchCommandTask(arg1) {
  return window['go']['main']['App']['CancelBatchCommandTask'](arg1);
}

export function CancelNetworkDiagnostic(arg1) {
  return window['go']['main']['App']['CancelNetworkDiagnostic'](arg1);
}

export function CancelSystemServiceRequests(arg1) {
  return window['go']['main']['App']['CancelSystemServiceRequests'](arg1);
}

export function CheckServiceManager(arg1) {
  return window['go']['main']['App']['CheckServiceManager'](arg1);
}

export function CheckShortcutConflicts(arg1) {
  return window['go']['main']['App']['CheckShortcutConflicts'](arg1);
}

export function CheckTunnelRemoteListen(arg1) {
  return window['go']['main']['App']['CheckTunnelRemoteListen'](arg1);
}

export function ClearBatchCommandTask(arg1) {
  return window['go']['main']['App']['ClearBatchCommandTask'](arg1);
}

export function ClearCommandHistory(arg1) {
  return window['go']['main']['App']['ClearCommandHistory'](arg1);
}

export function ClearResolvedAlertHistory(arg1) {
  return window['go']['main']['App']['ClearResolvedAlertHistory'](arg1);
}

export function CloseLocalTerminal(arg1) {
  return window['go']['main']['App']['CloseLocalTerminal'](arg1);
}

export function CloseNetworkInspectionContext(arg1) {
  return window['go']['main']['App']['CloseNetworkInspectionContext'](arg1);
}

export function CloseSftp(arg1) {
  return window['go']['main']['App']['CloseSftp'](arg1);
}

export function CloseSftpContext(arg1) {
  return window['go']['main']['App']['CloseSftpContext'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateCommandFavorite(arg1) {
  return window['go']['main']['App']['CreateCommandFavorite'](arg1);
}

export function CreateKeyVaultEntry(arg1) {
  return window['go']['main']['App']['CreateKeyVaultEntry'](arg1);
}

export function CreateTerminalProfile(arg1) {
  return window['go']['main']['App']['CreateTerminalProfile'](arg1);
}

export function CreateTunnelProfile(arg1) {
  return window['go']['main']['App']['CreateTunnelProfile'](arg1);
}

export function DeleteCommandFavorite(arg1) {
  return window['go']['main']['App']['DeleteCommandFavorite'](arg1);
}

export function DeleteCommandHistory(arg1) {
  return window['go']['main']['App']['DeleteCommandHistory'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteKeyVaultEntry(arg1) {
  return window['go']['main']['App']['DeleteKeyVaultEntry'](arg1);
}

export function DeleteKeyVaultPassphrase(arg1) {
  return window['go']['main']['App']['DeleteKeyVaultPassphrase'](arg1);
}

export function DeleteSavedCredential(arg1) {
  return window['go']['main']['App']['DeleteSavedCredential'](arg1);
}

export function DeleteTerminalProfile(arg1) {
  return window['go']['main']['App']['DeleteTerminalProfile'](arg1);
}

export function DeleteTunnelProfile(arg1) {
  return window['go']['main']['App']['DeleteTunnelProfile'](arg1);
}

export function DisableSystemService(arg1) {
  return window['go']['main']['App']['DisableSystemService'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DisconnectServer(arg1) {
  return window['go']['main']['App']['DisconnectServer'](arg1);
}

export function DockerBatchRemoveContainers(arg1) {
  return window['go']['main']['App']['DockerBatchRemoveContainers'](arg1);
}

export function DockerBatchRestartContainers(arg1) {
  return window['go']['main']['App']['DockerBatchRestartContainers'](arg1);
}

export function DockerBatchStartContainers(arg1) {
  return window['go']['main']['App']['DockerBatchStartContainers'](arg1);
}

export function DockerBatchStopContainers(arg1) {
  return window['go']['main']['App']['DockerBatchStopContainers'](arg1);
}

export function DockerCheck(arg1) {
  return window['go']['main']['App']['DockerCheck'](arg1);
}

export function DockerComposeCheck(arg1) {
  return window['go']['main']['App']['DockerComposeCheck'](arg1);
}

export function DockerComposeGetLogs(arg1) {
  return window['go']['main']['App']['DockerComposeGetLogs'](arg1);
}

export function DockerComposeGetServiceDetail(arg1) {
  return window['go']['main']['App']['DockerComposeGetServiceDetail'](arg1);
}

export function DockerComposeGetServices(arg1) {
  return window['go']['main']['App']['DockerComposeGetServices'](arg1);
}

export function DockerComposeListProjects(arg1) {
  return window['go']['main']['App']['DockerComposeListProjects'](arg1);
}

export function DockerGetContainerInspectSummary(arg1) {
  return window['go']['main']['App']['DockerGetContainerInspectSummary'](arg1);
}

export function DockerGetContainerLogs(arg1) {
  return window['go']['main']['App']['DockerGetContainerLogs'](arg1);
}

export function DockerGetContainerStats(arg1) {
  return window['go']['main']['App']['DockerGetContainerStats'](arg1);
}

export function DockerListContainers(arg1) {
  return window['go']['main']['App']['DockerListContainers'](arg1);
}

export function DockerRemoveContainer(arg1) {
  return window['go']['main']['App']['DockerRemoveContainer'](arg1);
}

export function DockerRestartContainer(arg1) {
  return window['go']['main']['App']['DockerRestartContainer'](arg1);
}

export function DockerStartContainer(arg1) {
  return window['go']['main']['App']['DockerStartContainer'](arg1);
}

export function DockerStartLogStream(arg1) {
  return window['go']['main']['App']['DockerStartLogStream'](arg1);
}

export function DockerStartStatsWatch(arg1) {
  return window['go']['main']['App']['DockerStartStatsWatch'](arg1);
}

export function DockerStopContainer(arg1) {
  return window['go']['main']['App']['DockerStopContainer'](arg1);
}

export function DockerStopLogStream(arg1) {
  return window['go']['main']['App']['DockerStopLogStream'](arg1);
}

export function DockerStopStatsWatch(arg1) {
  return window['go']['main']['App']['DockerStopStatsWatch'](arg1);
}

export function DuplicateTerminalProfile(arg1) {
  return window['go']['main']['App']['DuplicateTerminalProfile'](arg1);
}

export function EnableRemoteForwardAccess(arg1) {
  return window['go']['main']['App']['EnableRemoteForwardAccess'](arg1);
}

export function EnableRemoteForwardAccessAndRestart(arg1) {
  return window['go']['main']['App']['EnableRemoteForwardAccessAndRestart'](arg1);
}

export function EnableSystemService(arg1) {
  return window['go']['main']['App']['EnableSystemService'](arg1);
}

export function ExportBackup(arg1) {
  return window['go']['main']['App']['ExportBackup'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAuthenticationState(arg1) {
  return window['go']['main']['App']['GetAuthenticationState'](arg1);
}

export function GetBatchCommandTask(arg1) {
  return window['go']['main']['App']['GetBatchCommandTask'](arg1);
}

export function GetConnectionState(arg1) {
  return window['go']['main']['App']['GetConnectionState'](arg1);
}

export function GetDefaultSettings() {
  return window['go']['main']['App']['GetDefaultSettings']();
}

export function GetLocalDrives() {
  return window['go']['main']['App']['GetLocalDrives']();
}

export function GetLocalExplorerHome() {
  return window['go']['main']['App']['GetLocalExplorerHome']();
}

export function GetLocalResourceSnapshot() {
  return window['go']['main']['App']['GetLocalResourceSnapshot']();
}

export function GetLocalTerminalCapabilities() {
  return window['go']['main']['App']['GetLocalTerminalCapabilities']();
}

export function GetLocalTerminalState(arg1) {
  return window['go']['main']['App']['GetLocalTerminalState'](arg1);
}

export function GetMonitorNetworkInterface(arg1) {
  return window['go']['main']['App']['GetMonitorNetworkInterface'](arg1);
}

export function GetMonitorSnapshot(arg1) {
  return window['go']['main']['App']['GetMonitorSnapshot'](arg1);
}

export function GetNetworkEndpointSnapshot(arg1) {
  return window['go']['main']['App']['GetNetworkEndpointSnapshot'](arg1);
}

export function GetProcessDetail(arg1) {
  return window['go']['main']['App']['GetProcessDetail'](arg1);
}

export function GetResolvedTerminalProfile(arg1) {
  return window['go']['main']['App']['GetResolvedTerminalProfile'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSftpContextState(arg1) {
  return window['go']['main']['App']['GetSftpContextState'](arg1);
}

export function GetSftpState(arg1) {
  return window['go']['main']['App']['GetSftpState'](arg1);
}

export function GetStartupLocalTerminalRequest() {
  return window['go']['main']['App']['GetStartupLocalTerminalRequest']();
}

export function GetSystemServiceDetail(arg1) {
  return window['go']['main']['App']['GetSystemServiceDetail'](arg1);
}

export function GetSystemServiceJournal(arg1) {
  return window['go']['main']['App']['GetSystemServiceJournal'](arg1);
}

export function GetTunnelState(arg1) {
  return window['go']['main']['App']['GetTunnelState'](arg1);
}

export function ImportBackup(arg1) {
  return window['go']['main']['App']['ImportBackup'](arg1);
}

export function IncrementCommandFavoriteUse(arg1) {
  return window['go']['main']['App']['IncrementCommandFavoriteUse'](arg1);
}

export function InspectBackup(arg1) {
  return window['go']['main']['App']['InspectBackup'](arg1);
}

export function InspectRemoteForwardAccess(arg1) {
  return window['go']['main']['App']['InspectRemoteForwardAccess'](arg1);
}

export function ListAlertHistory(arg1) {
  return window['go']['main']['App']['ListAlertHistory'](arg1);
}

export function ListBatchCommandTasks() {
  return window['go']['main']['App']['ListBatchCommandTasks']();
}

export function ListCommandFavorites(arg1) {
  return window['go']['main']['App']['ListCommandFavorites'](arg1);
}

export function ListCommandHistory(arg1) {
  return window['go']['main']['App']['ListCommandHistory'](arg1);
}

export function ListCommandSuggestions(arg1) {
  return window['go']['main']['App']['ListCommandSuggestions'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListKeyVaultEntries() {
  return window['go']['main']['App']['ListKeyVaultEntries']();
}

export function ListLocalDirectory(arg1) {
  return window['go']['main']['App']['ListLocalDirectory'](arg1);
}

export function ListLocalTerminals() {
  return window['go']['main']['App']['ListLocalTerminals']();
}

export function ListLogs(arg1) {
  return window['go']['main']['App']['ListLogs'](arg1);
}

export function ListNetworkDiagnosticTasks(arg1) {
  return window['go']['main']['App']['ListNetworkDiagnosticTasks'](arg1);
}

export function ListNetworkInterfaces(arg1) {
  return window['go']['main']['App']['ListNetworkInterfaces'](arg1);
}

export function ListProcesses(arg1) {
  return window['go']['main']['App']['ListProcesses'](arg1);
}

export function ListSystemServices(arg1) {
  return window['go']['main']['App']['ListSystemServices'](arg1);
}

export function ListTerminalProfiles() {
  return window['go']['main']['App']['ListTerminalProfiles']();
}

export function ListTunnelProfiles() {
  return window['go']['main']['App']['ListTunnelProfiles']();
}

export function ListTunnels(arg1) {
  return window['go']['main']['App']['ListTunnels'](arg1);
}

export function LogFrontendError(arg1) {
  return window['go']['main']['App']['LogFrontendError'](arg1);
}

export function MarkAlertHistoryRead(arg1) {
  return window['go']['main']['App']['MarkAlertHistoryRead'](arg1);
}

export function MarkAllAlertHistoryRead(arg1) {
  return window['go']['main']['App']['MarkAllAlertHistoryRead'](arg1);
}

export function MigrateLegacyPrivateKey(arg1) {
  return window['go']['main']['App']['MigrateLegacyPrivateKey'](arg1);
}

export function OpenLocalPath(arg1) {
  return window['go']['main']['App']['OpenLocalPath'](arg1);
}

export function OpenLocalTerminal(arg1) {
  return window['go']['main']['App']['OpenLocalTerminal'](arg1);
}

export function OpenNetworkInspectionContext(arg1) {
  return window['go']['main']['App']['OpenNetworkInspectionContext'](arg1);
}

export function OpenSftp(arg1) {
  return window['go']['main']['App']['OpenSftp'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function PersistAlertHistoryEvent(arg1) {
  return window['go']['main']['App']['PersistAlertHistoryEvent'](arg1);
}

export function PersistWindowState() {
  return window['go']['main']['App']['PersistWindowState']();
}

export function ProbeConnectionReachability(arg1) {
  return window['go']['main']['App']['ProbeConnectionReachability'](arg1);
}

export function ProbeHostKey(arg1) {
  return window['go']['main']['App']['ProbeHostKey'](arg1);
}

export function ReadSftpDir(arg1) {
  return window['go']['main']['App']['ReadSftpDir'](arg1);
}

export function ReconnectSftp(arg1) {
  return window['go']['main']['App']['ReconnectSftp'](arg1);
}

export function ReconnectTerminal(arg1) {
  return window['go']['main']['App']['ReconnectTerminal'](arg1);
}

export function RecordBatchCommandHistory(arg1) {
  return window['go']['main']['App']['RecordBatchCommandHistory'](arg1);
}

export function RecordCommandHistory(arg1) {
  return window['go']['main']['App']['RecordCommandHistory'](arg1);
}

export function RelaunchElevatedLocalTerminal(arg1) {
  return window['go']['main']['App']['RelaunchElevatedLocalTerminal'](arg1);
}

export function ReorderServers(arg1) {
  return window['go']['main']['App']['ReorderServers'](arg1);
}

export function ResetHostKeyTrust(arg1) {
  return window['go']['main']['App']['ResetHostKeyTrust'](arg1);
}

export function ResizeLocalTerminal(arg1) {
  return window['go']['main']['App']['ResizeLocalTerminal'](arg1);
}

export function ResizeTerminal(arg1) {
  return window['go']['main']['App']['ResizeTerminal'](arg1);
}

export function RestartSystemService(arg1) {
  return window['go']['main']['App']['RestartSystemService'](arg1);
}

export function RestartTunnel(arg1) {
  return window['go']['main']['App']['RestartTunnel'](arg1);
}

export function RevealLocalPath(arg1) {
  return window['go']['main']['App']['RevealLocalPath'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveConnectionConfig(arg1) {
  return window['go']['main']['App']['SaveConnectionConfig'](arg1);
}

export function SaveGroup(arg1) {
  return window['go']['main']['App']['SaveGroup'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectBackupExportPath() {
  return window['go']['main']['App']['SelectBackupExportPath']();
}

export function SelectBackupImportFile() {
  return window['go']['main']['App']['SelectBackupImportFile']();
}

export function SelectLocalDownloadDirectory() {
  return window['go']['main']['App']['SelectLocalDownloadDirectory']();
}

export function SelectLocalUploadDirectory() {
  return window['go']['main']['App']['SelectLocalUploadDirectory']();
}

export function SelectLocalUploadFiles() {
  return window['go']['main']['App']['SelectLocalUploadFiles']();
}

export function SelectPrivateKeyFile() {
  return window['go']['main']['App']['SelectPrivateKeyFile']();
}

export function SetDefaultTerminalProfile(arg1) {
  return window['go']['main']['App']['SetDefaultTerminalProfile'](arg1);
}

export function SetMonitorNetworkInterface(arg1) {
  return window['go']['main']['App']['SetMonitorNetworkInterface'](arg1);
}

export function SftpCancelTransfer(arg1) {
  return window['go']['main']['App']['SftpCancelTransfer'](arg1);
}

export function SftpDelete(arg1) {
  return window['go']['main']['App']['SftpDelete'](arg1);
}

export function SftpDownload(arg1) {
  return window['go']['main']['App']['SftpDownload'](arg1);
}

export function SftpDownloadDirectory(arg1) {
  return window['go']['main']['App']['SftpDownloadDirectory'](arg1);
}

export function SftpGetRemoteItemProperties(arg1) {
  return window['go']['main']['App']['SftpGetRemoteItemProperties'](arg1);
}

export function SftpGoHome(arg1) {
  return window['go']['main']['App']['SftpGoHome'](arg1);
}

export function SftpGoParent(arg1) {
  return window['go']['main']['App']['SftpGoParent'](arg1);
}

export function SftpInspectDelete(arg1) {
  return window['go']['main']['App']['SftpInspectDelete'](arg1);
}

export function SftpMkdir(arg1) {
  return window['go']['main']['App']['SftpMkdir'](arg1);
}

export function SftpPauseTransfer(arg1) {
  return window['go']['main']['App']['SftpPauseTransfer'](arg1);
}

export function SftpReadTextFile(arg1) {
  return window['go']['main']['App']['SftpReadTextFile'](arg1);
}

export function SftpRename(arg1) {
  return window['go']['main']['App']['SftpRename'](arg1);
}

export function SftpResumeTransfer(arg1) {
  return window['go']['main']['App']['SftpResumeTransfer'](arg1);
}

export function SftpStat(arg1) {
  return window['go']['main']['App']['SftpStat'](arg1);
}

export function SftpUpdateRemoteItemPermissions(arg1) {
  return window['go']['main']['App']['SftpUpdateRemoteItemPermissions'](arg1);
}

export function SftpUpload(arg1) {
  return window['go']['main']['App']['SftpUpload'](arg1);
}

export function SftpUploadDirectory(arg1) {
  return window['go']['main']['App']['SftpUploadDirectory'](arg1);
}

export function SftpWriteTextFile(arg1) {
  return window['go']['main']['App']['SftpWriteTextFile'](arg1);
}

export function ShowLocalPathProperties(arg1) {
  return window['go']['main']['App']['ShowLocalPathProperties'](arg1);
}

export function SignalProcess(arg1) {
  return window['go']['main']['App']['SignalProcess'](arg1);
}

export function StartBatchCommand(arg1) {
  return window['go']['main']['App']['StartBatchCommand'](arg1);
}

export function StartNetworkDiagnostic(arg1) {
  return window['go']['main']['App']['StartNetworkDiagnostic'](arg1);
}

export function StartProcessWatch(arg1) {
  return window['go']['main']['App']['StartProcessWatch'](arg1);
}

export function StartSystemService(arg1) {
  return window['go']['main']['App']['StartSystemService'](arg1);
}

export function StartSystemServiceJournalFollow(arg1) {
  return window['go']['main']['App']['StartSystemServiceJournalFollow'](arg1);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopProcessWatch(arg1) {
  return window['go']['main']['App']['StopProcessWatch'](arg1);
}

export function StopSystemService(arg1) {
  return window['go']['main']['App']['StopSystemService'](arg1);
}

export function StopSystemServiceJournalFollow(arg1) {
  return window['go']['main']['App']['StopSystemServiceJournalFollow'](arg1);
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TrustHostKey(arg1) {
  return window['go']['main']['App']['TrustHostKey'](arg1);
}

export function UpdateCommandFavorite(arg1) {
  return window['go']['main']['App']['UpdateCommandFavorite'](arg1);
}

export function UpdateCommandHistory(arg1) {
  return window['go']['main']['App']['UpdateCommandHistory'](arg1);
}

export function UpdateKeyVaultEntry(arg1) {
  return window['go']['main']['App']['UpdateKeyVaultEntry'](arg1);
}

export function UpdateKeyVaultPassphrase(arg1, arg2) {
  return window['go']['main']['App']['UpdateKeyVaultPassphrase'](arg1, arg2);
}

export function UpdateTerminalProfile(arg1) {
  return window['go']['main']['App']['UpdateTerminalProfile'](arg1);
}

export function UpdateTunnelProfile(arg1) {
  return window['go']['main']['App']['UpdateTunnelProfile'](arg1);
}

export function ValidatePrivateKeyFile(arg1) {
  return window['go']['main']['App']['ValidatePrivateKeyFile'](arg1);
}

export function WriteLocalTerminal(arg1) {
  return window['go']['main']['App']['WriteLocalTerminal'](arg1);
}

export function WriteTerminal(arg1) {
  return window['go']['main']['App']['WriteTerminal'](arg1);
}
